### ISSUE TITLE
tg模式连接出错

### ISSUE THREAD

**Issue by knightlightningcp33** [TimeRainStarSky/Yunzai-Telegram-Plugin#1]
如图所示。
我在Yunzai\plugins\Telegram-Plugin\config.yaml中设置端口为clash的端口，然后显示如图：
![image](https://user-images.githubusercontent.com/130331299/232960004-e1af926c-c1e8-4f97-b682-b60864ba8df6.png)
然而无法连接。代理本身和端口没有问题
![image](https://user-images.githubusercontent.com/130331299/232959103-cb073908-7661-43a0-8364-2c27e2ff4b7b.png)

**Comment by TimeRainStarSky** [comment]
格式不对，应为 `scheme://[userinfo@]host[:port]`
举例：`socks5://localhost:7890`

**Comment by knightlightningcp33** [comment]
Edward
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "TimeRainStarSky/Yunzai-Telegram-Plugin"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年4月19日(星期三) 中午11:35
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [TimeRainStarSky/Yunzai-Telegram-Plugin] tg模式连接出错 (Issue #1)





 
格式不对，应为 scheme://[userinfo@]host[:port]
 举例：socks5://localhost:7890
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you authored the thread.Message ID: ***@***.***&gt;




原来如此，多谢

**Comment by bcrdvwz** [comment]
> 原来如此，多谢

兄弟你最后怎么解决的。试了sock5 http https都不行诶
![f434b91b9db18546063490b1eae4155f](https://github.com/TimeRainStarSky/Yunzai-Telegram-Plugin/assets/100638528/bac55159-32d0-4183-b57a-0ad9877d328d)
设置token还是提示账号连接失败
